### ISSUE TITLE
What should I do when the source and target vocabulary sizes differ significantly? Should I simply use the larger size?

### ISSUE THREAD

**Issue by aixiaodewugege** [facebookresearch/flow_matching#15]
Hi, thanks for the great repository! I’m using the code to transfer between two types of tokens. Can the current implementation handle this? Specifically, the source has 35,000 tokens, and the target has 512. Thank you!

**Comment by mhavasi** [comment]
I would recommend using a vocabulary size of 35512 if the tokens in the source and and target distributions are disjoint.

You can then train a DFM model with input size 35512 and output size 512 that you then pad to 35512 with zeros (assuming that the model predicts p1(x)).

**Comment by aixiaodewugege** [comment]
Thanks for your reply!

To clarify your suggestion: the source tokens range from 1 to 35,000, and the target tokens range from 1 to 512, but they are completely different representations. I should set the vocabulary size to 35,512; assign the target tokens to indices 35,001 to 35,512; train a DFM with an input size of 35,512 and an output size of 512; and pad the output to 35,512 with zeros.

Additionally, I am curious about why the output must be padded to 35,512.

**Comment by mhavasi** [comment]
Correct.

If the tokens correspond between the target set and source sets (i.e. they are the same 35000 tokens), then you should use a vocabulary size of 35000.

If the tokens are different between the target set and source sets (i.e. they are two disjoint sets of 35000 tokens), then you should use 70000.

**Comment by aixiaodewugege** [comment]
I trained the model, but the val dataset cross-entropy loss increases at the beginning of the training. Should I use the source token as a condition rather than providing it as X0?
![image](https://github.com/user-attachments/assets/3bd7ce36-b0ff-447b-a86c-68f0e99a88b1)

**Comment by mhavasi** [comment]
This will depend on your specific use case.

Closing this issue because the original question is answered and we cannot assist with specific use cases.
