### ISSUE TITLE
how about the conditional flow matching

### ISSUE THREAD

**Issue by sorobedio** [facebookresearch/flow_matching#16]
Thank you for your excellent work! It has been incredibly useful to me.

I was wondering if you could include code examples on conditional flow and sampling, as well as cross-distribution transfer. These additions would greatly enhance the understanding and applicability of the concepts.

Thank you once again!

**Comment by mhavasi** [comment]
Hey @sorobedio ,

In the paper (https://arxiv.org/pdf/2412.06264) we show the conditional flow matching loss on page 22 in Code 4. You can find a more detailed code example notebook at https://github.com/facebookresearch/flow_matching/blob/main/examples/2d_flow_matching.ipynb

We also provide larger scale examples for conditional image and text generation https://github.com/facebookresearch/flow_matching/tree/main/examples

**Comment by sorobedio** [comment]
Thank you for providing these valuable resources. They effectively addressed my questions. The image generation example, in particular, provided excellent clarity and demonstration.
I greatly appreciated reading this comprehensive guide. I wish you happy holidays and a wonderful end of year season.
Thank you again for your assistance.
