### ISSUE TITLE
Implementation on the metric-induced probability path

### ISSUE THREAD

**Issue by jinjinw** [facebookresearch/flow_matching#18]
Hi, there! Thanks for the amazing and comprehensive job on flow matching. 

I am currently on my way learning it, but coming across some questions. I notice that the current implementation does not involve this paper [Flow Matching with General Discrete Paths: A Kinetic-Optimal Perspective](https://arxiv.org/abs/2412.03487) on image generation so far, where I fail to find the metric d(·, ·) used to calculate p_t as described in the paper. 
Do you have plans to integrate this part to the codebase in the future?  

Look forward to your reply!

**Comment by rtqichen** [comment]
Possibly. Expect that we will include many of our research works, existing and future, into this repo, but we don't have exact dates or promises for anything yet.

**Comment by jinjinw** [comment]
Thanks for the reply. Look forward to your future update for the repo~
