### ISSUE TITLE
Possible wrong notation of collection functions

### ISSUE THREAD

**Issue by dianyo** [facebookresearch/flow_matching#23]
Hi,
I wonder if the notation of C in page 10 of the paper has a typo of n or m.
<img width="334" alt="Screenshot 2024-12-21 at 2 58 46 PM" src="https://github.com/user-attachments/assets/cb2e8bea-b834-4961-a5e0-f9d735a9a7b2" />

**Comment by mhavasi** [comment]
Thank you for flagging this. The correction will be included in the next release version of the paper.
