### ISSUE TITLE
a possible error in equ 4.13 and equ 4.14

### ISSUE THREAD

**Issue by shaaaaron** [facebookresearch/flow_matching#25]
![image](https://github.com/user-attachments/assets/c8bccc03-2c55-4ef6-ab36-3bd15a775be3)
![image](https://github.com/user-attachments/assets/d5b73512-d186-46f4-af59-a0583c99fb33)

As shown in the red box, it seems that $x$ should actually be $z$ here?

**Comment by mhavasi** [comment]
Thank you for flagging this. The fix will be included in version 2 of the paper.
