### ISSUE TITLE
a possible typo in VP, VE example between eq 4.70 and 4.71 in the paper

### ISSUE THREAD

**Issue by ValMystletainn** [facebookresearch/flow_matching#26]
![image](https://github.com/user-attachments/assets/53816352-343e-4b03-9713-f31ec77c9385)

I guess this is a typo, the first equation of the scheduler is the VE path and the second scheduler is VP path.

**Comment by mhavasi** [comment]
Thanks @ValMystletainn for catching this typo. The correction will be included in the next version of the paper.
