### ISSUE TITLE
Docs: incorrect link in docs index.html

### ISSUE THREAD

**Issue by mcclurmc** [facebookresearch/flow_matching#4]
Hello, I noticed that the link to "Flow Matching Guide and Codebase" on the [docs site](https://facebookresearch.github.io/flow_matching/) points to http://cnn.com, and not the actual codebase. [Here](https://github.com/facebookresearch/flow_matching/blob/dffe02b707ad89de8706d1e88dc5fc6d6d3847cc/docs/source/index.rst?plain=1#L5) is the source that should be updated.

**Comment by mhavasi** [comment]
Thats funny, I don't know how that happened ><

Thanks for flagging it.
