### ISSUE TITLE
Source code of the bespoke solver

### ISSUE THREAD

**Issue by qiyan98** [facebookresearch/flow_matching#5]
Hi there,

Thank you for open-sourcing the code on flow matching and the many impactful implementations built on top of this idea. I was wondering if the source code for 'Bespoke Solvers for Generative Flow Models' will also be released.

Best,
Qi

**Comment by itaigat** [comment]
Hi Qi,

We're currently prioritizing our upcoming feature releases. We'll update this issue if Bespoke is added to the roadmap.
